name: Actions workflow

on: [push]
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps: 
        - name: List files
          run: |
            pwd
            ls -a
        - name: checkout
          uses: actions/checkout@v3
        - name: List files After checkout
          run: |
            pwd
            ls -a
            echo $GITHUB_SHA
            echo $GITHUB_WORKSPACE
            echo $GITHUB_REPSITORY
       # - name: simple js action
       #   run: |
       #    pwd
       #     ls -a
       # - name: checkout
       #   uses: karthki/SaiJavaCode@master
       #  run: List file after checkout
       #     pwd
       #     ls -a