name: Actions workflow

on: [push]
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps: 
        - name: simple js action
          run: |
            pwd
            ls -a
        - name: checkout
          uses: karthki/SaiJavaCode@master
          run: List file after checkout
            pwd
            ls -a